services:
  pulse:
    build:
      context: .
      dockerfile: docker/pulse.Dockerfile
    ports:
      - "5603:5603"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://localhost:27017/}
      - TTL_HOURS=${TTL_HOURS:-48}
    restart: unless-stopped

  mercury:
    build:
      context: .
      dockerfile: docker/mercury.Dockerfile
    ports:
      - "5602:5602"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://localhost:27017/}
      - TTL_HOURS=${TTL_HOURS:-48}
    restart: unless-stopped
